#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v2
name: livycluster
description: Local Apache Livy and Spark development environment on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0-SNAPSHOT"
home: https://livy.apache.org/
sources:
  - https://github.com/apache/livy
maintainers:
  - name: Apache Livy
    email: livy@apache.org
keywords:
  - livy
  - spark
  - kubernetes
dependencies:
  - name: ingress-nginx
    version: 4.12.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
    tags:
      - ingress
  - name: cert-manager
    version: v1.16.2
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
    tags:
      - ingress
