#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "livycluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "livycluster.name" . }}
    helm.sh/chart: {{ include "livycluster.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.clusterHost | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.clusterHost | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "livycluster.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "livycluster.fullname" . }}-history-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "livycluster.historyLabels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Accept-Encoding "";
      sub_filter_last_modified off;
      sub_filter 'href="/' 'href="/historyserver/';
      sub_filter 'src="/' 'src="/historyserver/';
      sub_filter_once off;
      sub_filter_types text/html text/css text/javascript application/javascript;
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /historyserver
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.clusterHost | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.clusterHost | quote }}
      http:
        paths:
          - path: /historyserver/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "livycluster.fullname" . }}-history-service
                port:
                  number: 18080
{{- end }}
